#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

sudo yabai --load-sa

yabai -m config window_placement first_child

yabai -m config layout           bsp
yabai -m config window_gap       8
yabai -m config top_padding      6
yabai -m config bottom_padding   6
yabai -m config left_padding     6
yabai -m config right_padding    6

yabai -m config window_border off
